### ISSUE TITLE
Error Upon Installation

### ISSUE THREAD

**Issue by ss108** [alsatian-test/tap-bark#11]
I am suddenly getting this error when when installing Alsatian:

```
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path /node_modules/tap-bark/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/tap-bark/index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/tap-bark/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.

```

This wasn't happening before. The version of Alsatian I am installing is `1.0.0-beta.2`

**Comment by jamesadarich** [comment]
Hey Samier,

There was a problem with the files not being built before publish causing this issue, I've flagged the offending versions and published a new version (beta.10) so all should be good for you now :) I've also added a script to ensure the build will happen before publish and tests are run to avoid this in the future.

Let me know if all is good

Thanks,

James

**Comment by jamesadarich** [comment]
Closing as all my tests show fixed under retest, please reopen if otherwise :)

**Comment by ss108** [comment]
@jamesrichford 

Hey James,

Thanks for fixing, and sorry for the late reply. I get this error running Alsatian after reinstalling it--should I make an issue on the Alsatian repo?

`node_modules/alsatian/core/glob-helper.ts(1,23): error TS2307: Cannot find module 'glob'.`

**Comment by jamesadarich** [comment]
@ss108 

No problem Samier, happy belated Thanksgiving by the way!

Absolutely if you're still having trouble although my suspicion is that this is linked to https://github.com/alsatian-test/alsatian/issues/209 which was fixed in beta.3 so an upgrade may fix this :)

Let me know how you get on

Thanks,

James

**Comment by ss108** [comment]
@jamesrichford Reinstalled Alsatian and everything works fine. Thanks!

**Comment by jamesadarich** [comment]
@ss108 no problem :)
